spring:
  datasource:
    url: jdbc:mysql://duburani.csiv33i8vvhw.us-east-2.rds.amazonaws.com:3306/damdorani?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ekaehfksl0405
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: IwXJheScihgCM8f5iPOf
            client-secret: ngfzfBcSYq
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  port: 8089

