spring:
  datasource:
    url: jdbc:mysql://duburani.csiv33i8vvhw.us-east-2.rds.amazonaws.com:3306/damdorani?serverTimezone=Asia/Seoul&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ekaehfksl0405
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    ignore-default-model-on-redirect: false
  # naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: IwXJheScihgCM8f5iPOf
            client-secret: ngfzfBcSYq
            redirect-uri: "http://localhost:8089/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: da61026106bee083468e91e7f4f57ca6
            client-secret: nCIFsrRhRLbggT0ZVG3Ae2q1dmqpw1OL
            redirect-uri: "http://localhost:8089/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    token:
      secret-key: "6B64DCA4E72F58EDIKU9AAB215FE7"
      refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUri: "http://localhost:8089/oauth2/redirect"

decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  port: 8089

